//
//  FMStepID.swift
//  Rialto
//
//  Created by Richie Whyte on 21/07/2026.
//

import Foundation

/// Strongly-typed wrapper around FileMaker script step IDs
struct FMStepID: RawRepresentable, Hashable, Equatable, Codable, CustomStringConvertible {
    let rawValue: Int

    init(rawValue: Int) {
        self.rawValue = rawValue
    }

    // MARK: - Navigation Steps
    static let performScript              = FMStepID(rawValue: 1)
    static let saveCopyAsXML              = FMStepID(rawValue: 3)
    static let goToNextField              = FMStepID(rawValue: 4)
    static let goToPreviousField          = FMStepID(rawValue: 5)
    static let goToLayout                 = FMStepID(rawValue: 6)
    static let newRecordRequest           = FMStepID(rawValue: 7)
    static let duplicateRecordRequest     = FMStepID(rawValue: 8)
    static let deleteRecordRequest        = FMStepID(rawValue: 9)
    static let deleteAllRecords           = FMStepID(rawValue: 10)
    static let insertFromIndex            = FMStepID(rawValue: 11)
    static let insertFromLastVisited      = FMStepID(rawValue: 12)
    static let insertCurrentDate          = FMStepID(rawValue: 13)
    static let insertCurrentTime          = FMStepID(rawValue: 14)
    static let goToRecordRequestPage      = FMStepID(rawValue: 16)
    static let goToField                  = FMStepID(rawValue: 17)
    static let checkSelection             = FMStepID(rawValue: 18)
    static let checkRecord                = FMStepID(rawValue: 19)
    static let checkFoundSet              = FMStepID(rawValue: 20)
    static let unsortRecords              = FMStepID(rawValue: 21)
    static let enterFindMode              = FMStepID(rawValue: 22)
    static let showAllRecords             = FMStepID(rawValue: 23)
    static let modifyLastFind             = FMStepID(rawValue: 24)
    static let omitRecord                 = FMStepID(rawValue: 25)
    static let omitMultipleRecords        = FMStepID(rawValue: 26)
    static let showOmittedOnly            = FMStepID(rawValue: 27)
    static let performFind                = FMStepID(rawValue: 28)
    static let showHideToolbars           = FMStepID(rawValue: 29)
    static let viewAs                     = FMStepID(rawValue: 30)
    static let adjustWindow               = FMStepID(rawValue: 31)
    static let openHelp                   = FMStepID(rawValue: 32)
    static let openFile                   = FMStepID(rawValue: 33)
    static let closeFile                  = FMStepID(rawValue: 34)
    static let importRecords              = FMStepID(rawValue: 35)
    static let exportRecords              = FMStepID(rawValue: 36)
    static let saveCopyAs                 = FMStepID(rawValue: 37)
    static let openManageDatabase         = FMStepID(rawValue: 38)
    static let sortRecords                = FMStepID(rawValue: 39)
    static let relookupFieldContents      = FMStepID(rawValue: 40)
    static let enterPreviewMode           = FMStepID(rawValue: 41)
    static let printSetup                 = FMStepID(rawValue: 42)
    static let print                      = FMStepID(rawValue: 43)
    static let exitApplication            = FMStepID(rawValue: 44)
    static let undoRedo                   = FMStepID(rawValue: 45)
    static let cut                        = FMStepID(rawValue: 46)
    static let copy                       = FMStepID(rawValue: 47)
    static let paste                      = FMStepID(rawValue: 48)
    static let clearContent               = FMStepID(rawValue: 49)
    static let selectAll                  = FMStepID(rawValue: 50)
    static let revertRecordRequest        = FMStepID(rawValue: 51)
    static let enterBrowseMode            = FMStepID(rawValue: 55)
    static let insertPicture              = FMStepID(rawValue: 56)
    static let sendEvent                  = FMStepID(rawValue: 57)
    static let insertCurrentUserName      = FMStepID(rawValue: 60)
    static let insertText                 = FMStepID(rawValue: 61)
    static let pauseResumeScript          = FMStepID(rawValue: 62)
    static let sendMail                   = FMStepID(rawValue: 63)
    static let sendDDEExecute             = FMStepID(rawValue: 64)
    static let dialPhone                  = FMStepID(rawValue: 65)
    static let speak                      = FMStepID(rawValue: 66)
    static let performAppleScript         = FMStepID(rawValue: 67)

    // MARK: - Core Control Steps
    static let ifStep                     = FMStepID(rawValue: 68)
    static let elseStep                   = FMStepID(rawValue: 69)
    static let endIf                      = FMStepID(rawValue: 70)
    static let loop                       = FMStepID(rawValue: 71)
    static let exitLoopIf                 = FMStepID(rawValue: 72)
    static let endLoop                    = FMStepID(rawValue: 73)
    static let goToRelatedRecord          = FMStepID(rawValue: 74)
    static let commitRecords              = FMStepID(rawValue: 75)
    static let setField                   = FMStepID(rawValue: 76)
    static let insertCalculatedResult     = FMStepID(rawValue: 77)
    static let freezeWindow               = FMStepID(rawValue: 79)
    static let refreshWindow              = FMStepID(rawValue: 80)
    static let scrollWindow               = FMStepID(rawValue: 81)
    static let newFile                    = FMStepID(rawValue: 82)
    static let changePassword             = FMStepID(rawValue: 83)
    static let setMultiUser               = FMStepID(rawValue: 84)
    static let allowUserAbort             = FMStepID(rawValue: 85)
    static let setErrorCapture            = FMStepID(rawValue: 86)
    static let showCustomDialog           = FMStepID(rawValue: 87)
    static let openScriptWorkspace        = FMStepID(rawValue: 88)
    static let comment                    = FMStepID(rawValue: 89)
    static let haltScript                 = FMStepID(rawValue: 90)
    static let replaceFieldContents       = FMStepID(rawValue: 91)
    static let showHideTextRuler          = FMStepID(rawValue: 92)
    static let beep                       = FMStepID(rawValue: 93)
    static let setUseSystemFormats        = FMStepID(rawValue: 94)
    static let recoverFile                = FMStepID(rawValue: 95)
    static let saveCopyAsAddonPackage     = FMStepID(rawValue: 96)
    static let setZoomLevel               = FMStepID(rawValue: 97)
    static let copyAllRecordsRequests     = FMStepID(rawValue: 98)
    static let goToPortalRow              = FMStepID(rawValue: 99)
    static let copyRecordRequest          = FMStepID(rawValue: 101)
    static let flushCacheToDisk           = FMStepID(rawValue: 102)
    static let exitScript                 = FMStepID(rawValue: 103)
    static let deletePortalRow            = FMStepID(rawValue: 104)
    static let openSettings               = FMStepID(rawValue: 105)
    static let correctWord                = FMStepID(rawValue: 106)
    static let spellingOptions            = FMStepID(rawValue: 107)
    static let selectDictionaries         = FMStepID(rawValue: 108)
    static let editUserDictionary         = FMStepID(rawValue: 109)
    static let openURL                    = FMStepID(rawValue: 111)
    static let openManageValueLists       = FMStepID(rawValue: 112)
    static let openSharing                = FMStepID(rawValue: 113)
    static let openFileOptions            = FMStepID(rawValue: 114)
    static let allowFormattingBar         = FMStepID(rawValue: 115)
    static let setNextSerialValue         = FMStepID(rawValue: 116)
    static let executeSQL                 = FMStepID(rawValue: 117)
    static let openHosts                  = FMStepID(rawValue: 118)
    static let moveResizeWindow           = FMStepID(rawValue: 119)
    static let arrangeAllWindows          = FMStepID(rawValue: 120)
    static let closeWindow                = FMStepID(rawValue: 121)
    static let newWindow                  = FMStepID(rawValue: 122)
    static let selectWindow               = FMStepID(rawValue: 123)
    static let setWindowTitle             = FMStepID(rawValue: 124)
    static let elseIf                     = FMStepID(rawValue: 125)
    static let constrainFoundSet          = FMStepID(rawValue: 126)
    static let extendFoundSet             = FMStepID(rawValue: 127)
    static let performFindReplace         = FMStepID(rawValue: 128)
    static let openFindReplace            = FMStepID(rawValue: 129)
    static let setSelection               = FMStepID(rawValue: 130)
    static let insertFile                 = FMStepID(rawValue: 131)
    static let exportFieldContents        = FMStepID(rawValue: 132)
    static let openRecordRequest          = FMStepID(rawValue: 133)
    static let addAccount                 = FMStepID(rawValue: 134)
    static let deleteAccount              = FMStepID(rawValue: 135)
    static let resetAccountPassword       = FMStepID(rawValue: 136)
    static let enableAccount              = FMStepID(rawValue: 137)
    static let reLogin                    = FMStepID(rawValue: 138)
    static let convertFile                = FMStepID(rawValue: 139)
    static let openManageDataSources      = FMStepID(rawValue: 140)
    static let setVariable                = FMStepID(rawValue: 141)
    static let installMenuSet             = FMStepID(rawValue: 142)
    static let saveRecordsAsExcel         = FMStepID(rawValue: 143)
    static let saveRecordsAsPDF           = FMStepID(rawValue: 144)
    static let goToObject                 = FMStepID(rawValue: 145)
    static let setWebViewer               = FMStepID(rawValue: 146)
    static let setFieldByName             = FMStepID(rawValue: 147)
    static let installOnTimerScript       = FMStepID(rawValue: 148)
    static let openEditSavedFinds         = FMStepID(rawValue: 149)
    static let performQuickFind           = FMStepID(rawValue: 150)
    static let openManageLayouts          = FMStepID(rawValue: 151)
    static let saveRecordsAsSnapshotLink  = FMStepID(rawValue: 152)
    static let sortRecordsByField         = FMStepID(rawValue: 154)
    static let findMatchingRecords        = FMStepID(rawValue: 155)
    static let openManageContainers       = FMStepID(rawValue: 156)
    static let installPluginFile          = FMStepID(rawValue: 157)
    static let insertPDF                  = FMStepID(rawValue: 158)
    static let insertAudioVideo           = FMStepID(rawValue: 159)
    static let insertFromURL              = FMStepID(rawValue: 160)
    static let insertFromDevice           = FMStepID(rawValue: 161)
    static let performScriptOnServer      = FMStepID(rawValue: 164)
    static let openManageThemes           = FMStepID(rawValue: 165)
    static let showHideMenubar            = FMStepID(rawValue: 166)
    static let refreshObject              = FMStepID(rawValue: 167)
    static let setLayoutObjectAnimation   = FMStepID(rawValue: 168)
    static let closePopover               = FMStepID(rawValue: 169)
    static let openUploadToHost           = FMStepID(rawValue: 172)
    static let enableTouchKeyboard        = FMStepID(rawValue: 174)
    static let performJavaScriptInWebViewer = FMStepID(rawValue: 175)
    static let avPlayerPlay               = FMStepID(rawValue: 177)
    static let avPlayerSetPlaybackState   = FMStepID(rawValue: 178)
    static let avPlayerSetOptions         = FMStepID(rawValue: 179)
    static let refreshPortal              = FMStepID(rawValue: 180)
    static let getFolderPath              = FMStepID(rawValue: 181)
    static let truncateTable              = FMStepID(rawValue: 182)
    static let openFavorites              = FMStepID(rawValue: 183)
    static let configureRegionMonitor     = FMStepID(rawValue: 185)

    // MARK: - Hardware & Mobile
    static let configureLocalNotification = FMStepID(rawValue: 187)
    static let getFileExists              = FMStepID(rawValue: 188)
    static let getFileSize                = FMStepID(rawValue: 189)
    static let createDataFile             = FMStepID(rawValue: 190)
    static let openDataFile               = FMStepID(rawValue: 191)
    static let writeToDataFile            = FMStepID(rawValue: 192)
    static let readFromDataFile           = FMStepID(rawValue: 193)
    static let getDataFilePosition        = FMStepID(rawValue: 194)
    static let setDataFilePosition        = FMStepID(rawValue: 195)
    static let closeDataFile              = FMStepID(rawValue: 196)
    static let deleteFile                 = FMStepID(rawValue: 197)
    static let renameFile                 = FMStepID(rawValue: 199)
    static let setErrorLogging            = FMStepID(rawValue: 200)
    static let configureNFCReading        = FMStepID(rawValue: 201)
    static let configureMachineLearning   = FMStepID(rawValue: 202)
    static let executeFMDataAPI           = FMStepID(rawValue: 203)
    static let openTransaction            = FMStepID(rawValue: 205)
    static let commitTransaction          = FMStepID(rawValue: 206)
    static let revertTransaction          = FMStepID(rawValue: 207)
    static let setSessionIdentifier       = FMStepID(rawValue: 208)
    static let setDictionary              = FMStepID(rawValue: 209)
    static let performScriptOnServerWithCallback = FMStepID(rawValue: 210)
    static let triggerClarisConnectFlow   = FMStepID(rawValue: 211)

    // MARK: - AI Action Steps
    static let configureAIAccount         = FMStepID(rawValue: 212)
    static let fineTuneModel              = FMStepID(rawValue: 213)
    static let performSQLByNaturalLanguage = FMStepID(rawValue: 214)
    static let insertEmbedding             = FMStepID(rawValue: 215)
    static let insertEmbeddingInFoundSet   = FMStepID(rawValue: 216)
    static let setAICallLogging            = FMStepID(rawValue: 217)
    static let performSemanticFind         = FMStepID(rawValue: 218)
    static let performRAGAction            = FMStepID(rawValue: 219)
    static let generateResponse            = FMStepID(rawValue: 220)
    static let performFindByNaturalLanguage = FMStepID(rawValue: 221)
    static let configureRegressionModel    = FMStepID(rawValue: 222)
    static let setRevertTransactionOnError = FMStepID(rawValue: 223)
    static let saveRecordsAsJSONL          = FMStepID(rawValue: 225)
    static let configurePromptTemplate     = FMStepID(rawValue: 226)
    static let configureRAGAccount         = FMStepID(rawValue: 227)
    static let goToListOfRecords           = FMStepID(rawValue: 228)

    // MARK: - PDF Steps
    static let createPDF                  = FMStepID(rawValue: 243)
    static let closePDF                   = FMStepID(rawValue: 245)

    // MARK: - Helper Attributes
    var isBlockClosing: Bool {
        self == .endIf || self == .endLoop || self == .elseStep || self == .elseIf
    }

    var isBlockOpening: Bool {
        self == .ifStep || self == .loop || self == .elseStep || self == .elseIf
    }

    var description: String {
        return "\(rawValue)"
    }
}